INSERT INTO marketplace.categories
(category_id, category_name) 
VALUES 
(1, 'antiques'),
(2, 'appliances'),
(3, 'arts+crafts'),
(4, 'atvs / utvs / snowmobiles'),
(5, 'auto parts'),
(6, 'baby+kids'),
(7, 'barter'),
(8, 'bicycle parts'),
(9, 'bikes'),
(10, 'boat parts'),
(11, 'boats'),
(12, 'books'),
(13, 'business'),
(14, 'cars + trucks'),
(15, 'cds/dvd/vhs'),
(16, 'cell phones'),
(17, 'clothes+accessories'),
(18, 'collectibles'),
(19, 'computer parts'),
(20, 'computers+tech'),
(21, 'electronics'),
(22, 'farm+garden'),
(23, 'free stuff'),
(24, 'furniture'),
(25, 'garage & moving sales'),
(26, 'general'),
(27, 'health+beauty'),
(29, 'heavy equipment'),
(30, 'household'),
(31, 'jewelry'),
(32, 'materials'),
(33, 'motorcycle parts'),
(34, 'motorcycles/scooters'),
(35, 'musical instruments'),
(36, 'photo+video'),
(37, 'recreational vehicles'),
(38, 'sporting goods'),
(39, 'tickets'),
(40, 'tools'),
(41, 'toys+games'),
(42, 'video gaming'),
(43, 'wanted');